#!/usr/bin/env python
"""t2t-hvd-trainer."""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import sys, os
# sys.path.append('../')
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

import tensorflow as tf
from hvd import t2t_hvd_trainer


def main(argv):
    t2t_hvd_trainer.main(argv)


if __name__ == "__main__":
    tf.app.run()
